# configuration options: https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - /
      - /apps/main/
      - /packages/curve-ui-kit/
      - /packages/tsconfig/
      - /packages/prices-api/
      - /packages/eslint-config-custom/
      - /packages/ui/
      - /packages/external-rewards/
      - /tests/
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: immer
        update-types: ["version-update:semver-major"]
      - dependency-name: lightweight-charts
        update-types: ["version-update:semver-major"]
      - dependency-name: zustand
        update-types: ["version-update:semver-major"]
      - dependency-name: @curvefi/*  # curve updates done manually
    groups:
      react:
        patterns:
          - "*react*"
          - "*@tanstack*"
      onboard:
        patterns:
          - "*@safe-global*"
          - "*@web3-onboard*"
      storybook:
        patterns:
          - "@storybook*"
          - "storybook"
      typescript:
        patterns:
          - "*babel*"
          - "*eslint*"
          - "*tsconfig*"
          - "*typescript*"
          - "*webpack*"
      mui:
        patterns:
          - "*@mui*"
          - "*@hookform*"
      # Group minor updates in a single PR, major updates not matching above groups are separate PRs
      minor-updates:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
