name: CI
on: [push]
jobs:
  lint:
    timeout-minutes: 6
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v2
        with:
          node-version: 22
          cache: yarn
      - run: yarn set version stable
      - run: yarn install --immutable
      - run: yarn lint
      - run: yarn format:check
  cypress:
    strategy:
      fail-fast: false
      matrix:
        browser: [electron, firefox]
        flaky: [1, 2, 3, 4, 5, 6, 7, 8]
    name: Cypress in ${{ matrix.browser }} ${{ matrix.flaky }}
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn
      - run: npm install -g wait-on &

      - run: yarn set version stable
      - run: yarn install --immutable

      - name: Start dev server
        run: yarn run dev | tee dev-server.log &
        working-directory: apps/main

      - name: Wait for dev server
        # build apps in parallel, then wait for all of them sequentially
        run: |
          wait-on http://localhost:3000/dao/ & \
          wait-on http://localhost:3000/crvusd/ & \
          wait-on http://localhost:3000/lend/ & \
          wait-on http://localhost:3000/dex/ & \
          wait-on http://localhost:3000/
          wait-on http://localhost:3000/dao/
          wait-on http://localhost:3000/crvusd/
          wait-on http://localhost:3000/lend/
          wait-on http://localhost:3000/dex/
        working-directory: tests
      - run: yarn run cy:run:e2e --browser ${{ matrix.browser }}
        working-directory: tests
        env:
          ELECTRON_ENABLE_LOGGING: true # send console logs to stdout in electron browser

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-main-${{ matrix.browser }}-${{ matrix.flaky }}
          path: tests/cypress/screenshots
          retention-days: 1
          if-no-files-found: error

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: dev-server-log-${{ matrix.browser }}-${{ matrix.flaky }}
          if-no-files-found: error
          path: apps/main/dev-server.log
