name: Lint
on: [push]
jobs:
    lint:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v2
          with:
            node-version: 20
            cache: yarn
        - run: yarn set version stable
        - run: yarn install --immutable
        - run: yarn lint
