name: Prices API

on:
  push:
    tags:
      - prices-api/[0-9]+.[0-9]+.[0-9]+

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup NPM registry in Yarn
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: yarn
          registry-url: 'https://registry.npmjs.org'

      - name: 'Build and publish'
        working-directory: packages/prices-api
        run: |
          yarn install --immutable
          yarn npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
